version: "3.1"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client
    ports:
      - "3000:3000"
    restart: always
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server
    ports:
      - "3001:3001"
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shared_video
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
