name: luan
env:
      ##GITHUB_REPOSITORY: ${{ github.repository }}
      DEPLOY_PATH: /home/ubuntu/app-dev/${{ github.repository }}
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: start docker-compose file
        run: | 
            docker-compose up -d --build
            echo "successfully"
